server:
  port: 0

spring:
  application:
   name: kafka-consumer
  kafka:
    bootstrap-servers: localhost:29092
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres_user
    password: pass
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8085/eureka